21. Create NumPy Array of 5*6 integer elements  

a) Multiply the second element of third row by three    
b) Change one element to float, does it affect the others?  
c) Calculate row and column averages    
d) Create another array which contains first three rows and four columns of the original array  
e) Reshape the original array to 3 * 10 array     
f) Transpose the new 3 * 10 arrays    



In [47]:
# Create an array
import numpy as np
#Manually
num_array = np.array([[1,2,9,4,5],[6,3,6,5,4],[8,5,5,6,4],[5,0,4,5,3],[5,8,3,4,0],[1,5,2,3,0]])
#Or random
#num_array = np.random.randint(10, size=(5,6))
#print(num_array)

#a)
num_array[2,1] = num_array[2,1]*3


# b)
type(num_array[2,2])
#Change some other element to float
#num_array[3,1] = 3.5 #This doesn't work, because the data  type of entire array is int and also 3.5 will be converted to integer.
#All the elements have the same datatype!!
#Must convert the entire array to float:
num_array = num_array.astype(float)
num_array[3,1] = 3.5
print(num_array)

# c)
print('\n The average of all values is ', np.mean(num_array))
print('\n Column averages are ', np.mean(num_array, axis = 0))
print('\n Row averages are ', np.mean(num_array, axis = 1),'\n')

# d) 
new_array = num_array[0:3,0:4]
print('The limited array is \n',new_array,'\n')
print('The shape of new array is',new_array.shape)

#e ) Reshape to 3 times 10
#Note that the number of elements should match. 5*6 = 30 = 3*10
reshape_array = np.reshape(num_array,[3,10])
print('The new array with 3*10 dimensions is \n',reshape_array)

# f ) Transpose means that rows become columns and columns become rows
transpose_array = np.transpose(reshape_array)
#Or
#transpose_array = reshape_array.T
print('The transpose array s is \n',transpose_array)

[[ 1.   2.   9.   4.   5. ]
 [ 6.   3.   6.   5.   4. ]
 [ 8.  15.   5.   6.   4. ]
 [ 5.   3.5  4.   5.   3. ]
 [ 5.   8.   3.   4.   0. ]
 [ 1.   5.   2.   3.   0. ]]

 The average of all values is  4.483333333333333

 Column averages are  [4.33333333 6.08333333 4.83333333 4.5        2.66666667]

 Row averages are  [4.2 4.8 7.6 4.1 4.  2.2] 

The limited array is 
 [[ 1.  2.  9.  4.]
 [ 6.  3.  6.  5.]
 [ 8. 15.  5.  6.]] 

The shape of new array is (3, 4)
The new array with 3*10 dimensions is 
 [[ 1.   2.   9.   4.   5.   6.   3.   6.   5.   4. ]
 [ 8.  15.   5.   6.   4.   5.   3.5  4.   5.   3. ]
 [ 5.   8.   3.   4.   0.   1.   5.   2.   3.   0. ]]
The transpose array s is 
 [[ 1.   8.   5. ]
 [ 2.  15.   8. ]
 [ 9.   5.   3. ]
 [ 4.   6.   4. ]
 [ 5.   4.   0. ]
 [ 6.   5.   1. ]
 [ 3.   3.5  5. ]
 [ 6.   4.   2. ]
 [ 5.   5.   3. ]
 [ 4.   3.   0. ]]


22. Carry out the following basic operations on NumPy   

a) Create an array of 5 zeros.  
b) Create an array of 5 ones.   
c) Create two arrays: arr1 = [1, 2, 3, 4] and arr2 = [10, 20, 30, 40]. Perform element-wise addition, subtraction, multiplication, and division.    
d) Create an array with values from 1 to 12 (inclusive) and reshape it into a 3x4 matrix.   
e) Create a NumPy array with values [0, 5, 10, 15, 20]. Return all elements that are greater than 10    



In [66]:
# a)
zero_array = np.zeros(5) #Five zeros, floats!!!
#zero_array = np.zeros([5,5]) #5*5 zeros

#  b) 
one_array = np.ones(5)
#Or
#one_array = np.zeros(5) + 1 #This approach is good if you need something else than zeros or ones
one_array
#
#c) 
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
#Basic operations are simple and logical in Python. 
print('Element-wise addition arr1 + arr2 equals:', arr1 + arr2)
print('Element-wise substraction arr1 - arr2 equals:', arr1 - arr2)
print('Element-wise multiplication arr1 * arr2 equals:', arr1 * arr2)
print('Element-wise division arr1 * arr2 equals:', arr1 / arr2)

#d) We often need this type of array
array_12 = np.arange(1,13,1)
print('The array from 1 to 12 \n',array_12 )
reshape_array_12 = np.reshape(array_12,[3,4]) 
print('\n Reshaped array is \n', reshape_array_12)

#e)
array_last = np.array([0,5,10,15,20])
#Define a new variable:
greater_than_10 = array_last[array_last>10]
print('\n Values larger than 10 are:', greater_than_10)


Element-wise addition arr1 + arr2 equals: [11 22 33 44]
Element-wise substraction arr1 - arr2 equals: [ -9 -18 -27 -36]
Element-wise multiplication arr1 * arr2 equals: [ 10  40  90 160]
Element-wise division arr1 * arr2 equals: [0.1 0.1 0.1 0.1]
The array from 1 to 12 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

 Reshaped array is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Values larger than 10 are: [15 20]


23. Compare NumPy and Pandas arrays. Which one you prefer for different purposes? What are pros and cons?   

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Numpy:
# - Mathematical
# - Fast
# - Supports data with large dimensions (multidimensional, large number of columns)
#NumPy is a tool for heavy number crushing

#Pandas
# - DataFrame "table/spreadsheet feeling"
# - Headers are nice (know what you have)
# - DataFrames allow higher level operations (SQL-type: groups, merge, join)
# - DataFrame allow multiple data types (but only one per column)

#Conclusion:
#Use Pandas if you can.


