In [8]:
#Exercise 33
import numpy as np 
#Define vectors
a = np.array([3,-2,1])
b = np.array([-2,1,-5])
print('The magnitude of a is', np.round(np.linalg.norm(a),2))
print('The magnitude of b is', np.round(np.linalg.norm(b),2))
print('b - a is:', b - a)
print('The magnitude of b - a is', np.round(np.linalg.norm(b - a),2))

The magnitude of a is 3.74
The magnitude of b is 5.48
b - a is: [-5  3 -6]
The magnitude of b - a is 8.37


In [10]:
#34
a = np.array([4,-2,-1])
b = np.array([3,-3,3])
c = np.array([2,-1,-1])
print('The dot product of a and a is', np.dot(a,a))
print('The dot product of a and b is', np.dot(a,b))
print('The dot product of a and c is', np.dot(a,c))
print('The dot product of b and c is', np.dot(b,c))

The dot product of a and a is 21
The dot product of a and b is 15
The dot product of a and c is 11
The dot product of b and c is 6


In [ ]:
#36
A = np.array([1,-3,5])
B = np.array([-2,1,4])
print('The magnitude of A is', np.round(np.linalg.norm(A),2))
print('The magnitude of B is', np.round(np.linalg.norm(B),2))
print('Sum of A and B is', A + B)
print('The dot product of A and B is', np.dot(A,B))
print('5A is', 5*A)
print('The dot product of A and 5B is', np.dot(A,5*B))
print('The cross product of A and B is', np.cross(A,B)) #Gives a vector perpendicular to A and B. 
#If A and B are parallel, cross product is zero

The magnitude of A is 5.92
The magnitude of B is 4.58
Sum of A and B is [-1 -2  9]
The dot product of A and B is 15
5A is [  5 -15  25]
The dot product of A and 5B is 75
The cross product of A and B is [-17 -14  -5]


In [ ]:
#37
A = np.array([[1,1,1],[2,1,0],[3,-1,2]])
B = np.array([[0,3,1],[4,-1,0],[2,2,1]])
#Multiplication
print('The product of A and B is \n' , np.matmul(A,B))
print('\n The product of B and A is \n' , np.matmul(B,A))

#Matric multiplication is not cummutative, AB is different from BA

The product of A and B is 
 [[ 6  4  2]
 [ 4  5  2]
 [ 0 14  5]]

 The product of B and A is 
 [[9 2 2]
 [2 3 4]
 [9 3 4]]


In [28]:
#Exercise 38
A = np.array([[4,2,-5,6],[1,-2,9,2],[0,3,11,4]])
B = np.array([[2,5,-5,3],[3,4,-9,-2],[-7,1,1,0]])
print('Matix A is \n', A)
print('\n Matix B is \n', B)
print('\n The sum A + B is \n', A + B) #Summing matrices element by element
print('\n Transpose of A is \n', np.transpose(A)) #rows become colums and columns became rows
print('\n Transpose of B is \n', np.transpose(B))
print('The product of A and transpose of B is \n' , np.matmul(A,np.transpose(B)))

Matix A is 
 [[ 4  2 -5  6]
 [ 1 -2  9  2]
 [ 0  3 11  4]]

 Matix B is 
 [[ 2  5 -5  3]
 [ 3  4 -9 -2]
 [-7  1  1  0]]

 The sum A + B is 
 [[  6   7 -10   9]
 [  4   2   0   0]
 [ -7   4  12   4]]

 Transpose of A is 
 [[ 4  1  0]
 [ 2 -2  3]
 [-5  9 11]
 [ 6  2  4]]

 Transpose of B is 
 [[ 2  3 -7]
 [ 5  4  1]
 [-5 -9  1]
 [ 3 -2  0]]
The product of A and transpose of B is 
 [[ 61  53 -31]
 [-47 -90   0]
 [-28 -95  14]]
